export const SEED_TOPICS = [
    { name: "Daily Life", description: "Cuộc sống hàng ngày, thói quen và sinh hoạt", icon: "Coffee", order: 1 },
    { name: "Family", description: "Gia đình, người thân và mối quan hệ họ hàng", icon: "Users", order: 2 },
    { name: "School", description: "Trường học, lớp học và các môn học", icon: "GraduationCap", order: 3 },
    { name: "Work", description: "Công việc, văn phòng và nghề nghiệp", icon: "Briefcase", order: 4 },
    { name: "Travel", description: "Du lịch, di chuyển, kỳ nghỉ và phương tiện", icon: "Plane", order: 5 },
    { name: "Food", description: "Ẩm thực, món ăn, nấu nướng và nhà hàng", icon: "Utensils", order: 6 },
    { name: "Shopping", description: "Mua sắm, giá cả, thời trang và thanh toán", icon: "ShoppingBag", order: 7 },
    { name: "Health", description: "Sức khỏe, thể dục, y tế và lối sống lành mạnh", icon: "HeartPulse", order: 8 },
    { name: "Technology", description: "Công nghệ số, máy tính, AI và Internet", icon: "Laptop", order: 9 },
    { name: "Environment", description: "Môi trường, thiên nhiên và biến đổi khí hậu", icon: "Trees", order: 10 },
    { name: "Entertainment", description: "Giải trí, âm nhạc, phim ảnh và nghệ thuật", icon: "Film", order: 11 },
    { name: "Relationships", description: "Bạn bè, tình bạn và giao tiếp xã hội", icon: "UserCheck", order: 12 },
    { name: "Sports", description: "Thể thao, thi đấu và rèn luyện thể chất", icon: "Trophy", order: 13 },
    { name: "Business", description: "Kinh doanh, thị trường và tài chính", icon: "TrendingUp", order: 14 },
    { name: "Education", description: "Giáo dục, phương pháp học và tri thức", icon: "BookOpen", order: 15 },
];

export const SEED_GRAMMAR = [
    { name: "Present Simple", description: "Thì hiện tại đơn diễn tả chân lý, thói quen", level: "A1", order: 1 },
    { name: "Present Continuous", description: "Thì hiện tại tiếp diễn tả hành động đang xảy ra", level: "A1", order: 2 },
    { name: "Past Simple", description: "Thì quá khứ đơn diễn tả sự việc đã kết thúc", level: "A2", order: 3 },
    { name: "Past Continuous", description: "Thì quá khứ tiếp diễn diễn tả hành động đang xảy ra trong quá khứ", level: "A2", order: 4 },
    { name: "Present Perfect", description: "Thì hiện tại hoàn thành liên kết quá khứ với hiện tại", level: "B1", order: 5 },
    { name: "Future Simple", description: "Thì tương lai đơn diễn tả quyết định nhất thời hoặc dự đoán", level: "A1", order: 6 },
    { name: "Be going to", description: "Tương lai gần diễn tả kế hoạch hoặc dự đoán có căn cứ", level: "A2", order: 7 },
    { name: "Modal Verbs", description: "Động từ khiếm khuyết (can, could, should, must, might)", level: "A2", order: 8 },
    { name: "Articles", description: "Mạo từ xác định và không xác định (a, an, the, zero article)", level: "A1", order: 9 },
    { name: "Prepositions", description: "Giới từ chỉ thời gian, nơi chốn và phương hướng", level: "A1", order: 10 },
    { name: "Comparatives", description: "Cấu trúc so sánh hơn của tính từ và trạng từ", level: "A2", order: 11 },
    { name: "Superlatives", description: "Cấu trúc so sánh nhất", level: "A2", order: 12 },
    { name: "Conditionals", description: "Câu điều kiện loại 0, 1, 2, 3 và hỗn hợp", level: "B1", order: 13 },
    { name: "Passive Voice", description: "Câu bị động theo các thì", level: "B1", order: 14 },
    { name: "Relative Clauses", description: "Mệnh đề quan hệ xác định và không xác định", level: "B2", order: 15 },
    { name: "Reported Speech", description: "Câu tường thuật gián tiếp", level: "B2", order: 16 },
    { name: "Subject-Verb Agreement", description: "Sự hòa hợp giữa chủ ngữ và động từ", level: "A2", order: 17 },
    { name: "Gerunds & Infinitives", description: "Danh động từ và động từ nguyên mẫu", level: "B1", order: 18 },
];

export const SEED_QUESTIONS = [
    // A1 (15 questions)
    {
        vietnameseSentence: "Tôi thức dậy lúc 6 giờ sáng mỗi ngày.",
        referenceAnswer: "I wake up at 6 AM every day.",
        alternativeAnswers: ["I get up at 6 in the morning every day.", "Every day, I wake up at 6 o'clock in the morning."],
        level: "A1",
        topic: "Daily Life",
        grammarTopic: "Present Simple",
        difficulty: "easy",
        keywords: ["wake up", "every day", "6 AM"],
    },
    {
        vietnameseSentence: "Cô ấy có hai người anh trai và một người chị gái.",
        referenceAnswer: "She has two brothers and one sister.",
        alternativeAnswers: ["She has two older brothers and a sister.", "She's got two brothers and one sister."],
        level: "A1",
        topic: "Family",
        grammarTopic: "Present Simple",
        difficulty: "easy",
        keywords: ["have/has", "brothers", "sister"],
    },
    {
        vietnameseSentence: "Tôi đang đọc một cuốn sách thú vị.",
        referenceAnswer: "I am reading an interesting book.",
        alternativeAnswers: ["I'm reading a fascinating book.", "Currently, I am reading an interesting book."],
        level: "A1",
        topic: "Education",
        grammarTopic: "Present Continuous",
        difficulty: "easy",
        keywords: ["reading", "interesting book", "an"],
    },
    {
        vietnameseSentence: "Thời tiết hôm nay rất đẹp và nhiều nắng.",
        referenceAnswer: "The weather today is very nice and sunny.",
        alternativeAnswers: ["Today's weather is really beautiful and sunny.", "It is very nice and sunny today."],
        level: "A1",
        topic: "Daily Life",
        grammarTopic: "Articles",
        difficulty: "easy",
        keywords: ["the weather", "sunny", "nice"],
    },
    {
        vietnameseSentence: "Anh ấy không thích ăn đồ ăn cay.",
        referenceAnswer: "He does not like eating spicy food.",
        alternativeAnswers: ["He doesn't like spicy food.", "He dislikes eating spicy dishes."],
        level: "A1",
        topic: "Food",
        grammarTopic: "Present Simple",
        difficulty: "easy",
        keywords: ["doesn't like", "spicy food"],
    },
    {
        vietnameseSentence: "Chúng tôi sống trong một căn hộ nhỏ ở Hà Nội.",
        referenceAnswer: "We live in a small apartment in Hanoi.",
        alternativeAnswers: ["We live in a small flat in Hanoi.", "We are living in a small apartment in Hanoi."],
        level: "A1",
        topic: "Daily Life",
        grammarTopic: "Prepositions",
        difficulty: "easy",
        keywords: ["live in", "small apartment", "Hanoi"],
    },
    {
        vietnameseSentence: "Mẹ tôi nấu ăn rất ngon vào mỗi cuối tuần.",
        referenceAnswer: "My mother cooks very well every weekend.",
        alternativeAnswers: ["My mom cooks very delicious food every weekend.", "My mother is a great cook on weekends."],
        level: "A1",
        topic: "Family",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "easy",
        keywords: ["mother cooks", "very well", "every weekend"],
    },
    {
        vietnameseSentence: "Bạn có thể nói tiếng Anh không?",
        referenceAnswer: "Can you speak English?",
        alternativeAnswers: ["Are you able to speak English?", "Do you speak English?"],
        level: "A1",
        topic: "Education",
        grammarTopic: "Modal Verbs",
        difficulty: "easy",
        keywords: ["can", "speak English"],
    },
    {
        vietnameseSentence: "Chiếc áo sơ mi này giá bao nhiêu tiền?",
        referenceAnswer: "How much is this shirt?",
        alternativeAnswers: ["How much does this shirt cost?", "What is the price of this shirt?"],
        level: "A1",
        topic: "Shopping",
        grammarTopic: "Present Simple",
        difficulty: "easy",
        keywords: ["how much", "this shirt"],
    },
    {
        vietnameseSentence: "Họ đang chơi bóng đá trong công viên.",
        referenceAnswer: "They are playing football in the park.",
        alternativeAnswers: ["They're playing soccer in the park.", "They are playing football at the park."],
        level: "A1",
        topic: "Sports",
        grammarTopic: "Present Continuous",
        difficulty: "easy",
        keywords: ["playing football", "in the park"],
    },
    {
        vietnameseSentence: "Tôi sẽ gọi cho bạn vào ngày mai.",
        referenceAnswer: "I will call you tomorrow.",
        alternativeAnswers: ["I'll call you tomorrow.", "I will give you a call tomorrow."],
        level: "A1",
        topic: "Relationships",
        grammarTopic: "Future Simple",
        difficulty: "easy",
        keywords: ["will call", "tomorrow"],
    },
    {
        vietnameseSentence: "Cuốn sách ở trên chiếc bàn cạnh cửa sổ.",
        referenceAnswer: "The book is on the table next to the window.",
        alternativeAnswers: ["The book is on the desk by the window."],
        level: "A1",
        topic: "Daily Life",
        grammarTopic: "Prepositions",
        difficulty: "easy",
        keywords: ["on the table", "next to"],
    },
    {
        vietnameseSentence: "Anh ấy luôn uống một tách cà phê vào buổi sáng.",
        referenceAnswer: "He always drinks a cup of coffee in the morning.",
        alternativeAnswers: ["He always has a cup of coffee in the morning."],
        level: "A1",
        topic: "Daily Life",
        grammarTopic: "Present Simple",
        difficulty: "easy",
        keywords: ["always drinks", "a cup of coffee"],
    },
    {
        vietnameseSentence: "Có ba quả táo ở trong tủ lạnh.",
        referenceAnswer: "There are three apples in the fridge.",
        alternativeAnswers: ["There are three apples in the refrigerator."],
        level: "A1",
        topic: "Food",
        grammarTopic: "Articles",
        difficulty: "easy",
        keywords: ["there are", "in the fridge"],
    },
    {
        vietnameseSentence: "Tôi thích nghe nhạc khi tôi làm bài tập về nhà.",
        referenceAnswer: "I like listening to music when I do my homework.",
        alternativeAnswers: ["I enjoy listening to music while doing homework."],
        level: "A1",
        topic: "Entertainment",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "easy",
        keywords: ["listening to music", "homework"],
    },

    // A2 (15 questions)
    {
        vietnameseSentence: "Tôi đã đi Đà Nẵng vào mùa hè năm ngoái.",
        referenceAnswer: "I went to Da Nang last summer.",
        alternativeAnswers: ["Last summer, I travelled to Da Nang.", "I visited Da Nang last summer."],
        level: "A2",
        topic: "Travel",
        grammarTopic: "Past Simple",
        difficulty: "medium",
        keywords: ["went to", "last summer", "Da Nang"],
    },
    {
        vietnameseSentence: "Hôm qua khi tôi đang xem TV thì trời bắt đầu mưa.",
        referenceAnswer: "Yesterday, while I was watching TV, it started to rain.",
        alternativeAnswers: ["It started raining while I was watching TV yesterday.", "When I was watching TV yesterday, it started raining."],
        level: "A2",
        topic: "Daily Life",
        grammarTopic: "Past Continuous",
        difficulty: "medium",
        keywords: ["was watching", "started to rain"],
    },
    {
        vietnameseSentence: "Chiếc xe hơi này đắt hơn chiếc xe hơi kia.",
        referenceAnswer: "This car is more expensive than that car.",
        alternativeAnswers: ["This car is more expensive than that one.", "This vehicle costs more than that one."],
        level: "A2",
        topic: "Shopping",
        grammarTopic: "Comparatives",
        difficulty: "easy",
        keywords: ["more expensive than"],
    },
    {
        vietnameseSentence: "Anh ấy là học sinh thông minh nhất trong lớp tôi.",
        referenceAnswer: "He is the smartest student in my class.",
        alternativeAnswers: ["He is the most intelligent student in my class."],
        level: "A2",
        topic: "School",
        grammarTopic: "Superlatives",
        difficulty: "medium",
        keywords: ["the smartest", "in my class"],
    },
    {
        vietnameseSentence: "Chúng tôi dự định sẽ đi cắm trại vào cuối tuần này.",
        referenceAnswer: "We are going to go camping this weekend.",
        alternativeAnswers: ["We plan to go camping this weekend.", "We are planning a camping trip this weekend."],
        level: "A2",
        topic: "Travel",
        grammarTopic: "Be going to",
        difficulty: "medium",
        keywords: ["are going to", "go camping", "this weekend"],
    },
    {
        vietnameseSentence: "Bạn nên uống nhiều nước hơn khi bạn bị ốm.",
        referenceAnswer: "You should drink more water when you are sick.",
        alternativeAnswers: ["You ought to drink more water when feeling sick.", "You should drink plenty of water if you are unwell."],
        level: "A2",
        topic: "Health",
        grammarTopic: "Modal Verbs",
        difficulty: "medium",
        keywords: ["should drink", "more water", "sick"],
    },
    {
        vietnameseSentence: "Tôi không tìm thấy chìa khóa xe máy của mình ở đâu cả.",
        referenceAnswer: "I cannot find my motorbike keys anywhere.",
        alternativeAnswers: ["I can't find my motorbike keys anywhere.", "I am unable to find my motorcycle keys anywhere."],
        level: "A2",
        topic: "Daily Life",
        grammarTopic: "Modal Verbs",
        difficulty: "medium",
        keywords: ["cannot find", "motorbike keys", "anywhere"],
    },
    {
        vietnameseSentence: "Năm ngoái, cô ấy đã mua một chiếc máy tính xách tay mới để làm việc.",
        referenceAnswer: "Last year, she bought a new laptop for work.",
        alternativeAnswers: ["She bought a new laptop for work last year.", "Last year, she purchased a new laptop for her job."],
        level: "A2",
        topic: "Technology",
        grammarTopic: "Past Simple",
        difficulty: "medium",
        keywords: ["bought", "new laptop", "last year"],
    },
    {
        vietnameseSentence: "Nếu ngày mai trời mưa, chúng tôi sẽ ở nhà.",
        referenceAnswer: "If it rains tomorrow, we will stay at home.",
        alternativeAnswers: ["We will stay home if it rains tomorrow."],
        level: "A2",
        topic: "Daily Life",
        grammarTopic: "Conditionals",
        difficulty: "medium",
        keywords: ["if it rains", "will stay at home"],
    },
    {
        vietnameseSentence: "Bố tôi đã làm việc tại công ty này được 10 năm rồi.",
        referenceAnswer: "My father has worked at this company for 10 years.",
        alternativeAnswers: ["My dad has been working in this company for 10 years."],
        level: "A2",
        topic: "Work",
        grammarTopic: "Present Perfect",
        difficulty: "medium",
        keywords: ["has worked", "for 10 years"],
    },
    {
        vietnameseSentence: "Tôi thích bơi lội hơn là chạy bộ trong công viên.",
        referenceAnswer: "I prefer swimming to running in the park.",
        alternativeAnswers: ["I like swimming more than running in the park."],
        level: "A2",
        topic: "Sports",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "medium",
        keywords: ["prefer swimming to", "in the park"],
    },
    {
        vietnameseSentence: "Họ đã không tham gia bữa tiệc sinh nhật tối qua.",
        referenceAnswer: "They did not attend the birthday party last night.",
        alternativeAnswers: ["They didn't come to the birthday party last night."],
        level: "A2",
        topic: "Entertainment",
        grammarTopic: "Past Simple",
        difficulty: "medium",
        keywords: ["did not attend", "last night"],
    },
    {
        vietnameseSentence: "Thành phố này đông đúc hơn thị trấn quê tôi.",
        referenceAnswer: "This city is more crowded than my hometown.",
        alternativeAnswers: ["This city is much more crowded than the town I grew up in."],
        level: "A2",
        topic: "Travel",
        grammarTopic: "Comparatives",
        difficulty: "medium",
        keywords: ["more crowded than", "hometown"],
    },
    {
        vietnameseSentence: "Bạn phải đeo khẩu trang khi vào bệnh viện.",
        referenceAnswer: "You must wear a mask when entering the hospital.",
        alternativeAnswers: ["You have to wear a face mask when you go into the hospital."],
        level: "A2",
        topic: "Health",
        grammarTopic: "Modal Verbs",
        difficulty: "medium",
        keywords: ["must wear", "a mask", "hospital"],
    },
    {
        vietnameseSentence: "Tôi vừa mới hoàn thành xong bài tập về nhà môn Tiếng Anh.",
        referenceAnswer: "I have just finished my English homework.",
        alternativeAnswers: ["I've just finished doing my English homework."],
        level: "A2",
        topic: "School",
        grammarTopic: "Present Perfect",
        difficulty: "medium",
        keywords: ["have just finished", "English homework"],
    },

    // B1 (20 questions)
    {
        vietnameseSentence: "Tôi đã sống ở thành phố này từ khi tôi tốt nghiệp đại học.",
        referenceAnswer: "I have lived in this city since I graduated from university.",
        alternativeAnswers: ["I have been living in this city since graduating from college.", "Ever since I graduated from university, I have lived in this city."],
        level: "B1",
        topic: "Work",
        grammarTopic: "Present Perfect",
        difficulty: "medium",
        keywords: ["have lived", "since", "graduated"],
    },
    {
        vietnameseSentence: "Nếu tôi có nhiều thời gian rảnh hơn, tôi sẽ học thêm một ngôn ngữ mới.",
        referenceAnswer: "If I had more free time, I would learn a new language.",
        alternativeAnswers: ["If I had more spare time, I'd study another language.", "Were I to have more free time, I would learn an additional language."],
        level: "B1",
        topic: "Education",
        grammarTopic: "Conditionals",
        difficulty: "medium",
        keywords: ["if I had", "would learn"],
    },
    {
        vietnameseSentence: "Cây cầu này được xây dựng bởi các kỹ sư hàng đầu vào năm 2010.",
        referenceAnswer: "This bridge was built by top engineers in 2010.",
        alternativeAnswers: ["This bridge was constructed by leading engineers in 2010."],
        level: "B1",
        topic: "Technology",
        grammarTopic: "Passive Voice",
        difficulty: "medium",
        keywords: ["was built by", "engineers"],
    },
    {
        vietnameseSentence: "Cô gái người mà đang nói chuyện với thầy giáo là bạn thân nhất của tôi.",
        referenceAnswer: "The girl who is talking to the teacher is my best friend.",
        alternativeAnswers: ["The girl who is speaking with the teacher is my best friend."],
        level: "B1",
        topic: "School",
        grammarTopic: "Relative Clauses",
        difficulty: "medium",
        keywords: ["the girl who is talking", "best friend"],
    },
    {
        vietnameseSentence: "Mặc dù trời mưa rất to, chúng tôi vẫn quyết định đi bộ đường dài.",
        referenceAnswer: "Although it rained heavily, we still decided to go hiking.",
        alternativeAnswers: ["Despite the heavy rain, we decided to go hiking anyway.", "Even though it was raining heavily, we went hiking."],
        level: "B1",
        topic: "Travel",
        grammarTopic: "Conditionals",
        difficulty: "medium",
        keywords: ["although", "rained heavily", "go hiking"],
    },
    {
        vietnameseSentence: "Anh ấy nói với tôi rằng anh ấy sẽ chuyển đến Luân Đôn vào tháng tới.",
        referenceAnswer: "He told me that he would move to London the following month.",
        alternativeAnswers: ["He told me that he was going to move to London next month.", "He mentioned to me that he would relocate to London next month."],
        level: "B1",
        topic: "Relationships",
        grammarTopic: "Reported Speech",
        difficulty: "medium",
        keywords: ["told me that", "would move"],
    },
    {
        vietnameseSentence: "Học ngoại ngữ đòi hỏi sự kiên trì và thực hành thường xuyên.",
        referenceAnswer: "Learning a foreign language requires patience and regular practice.",
        alternativeAnswers: ["Studying a foreign language demands persistence and consistent practice."],
        level: "B1",
        topic: "Education",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "medium",
        keywords: ["learning a foreign language", "requires", "patience"],
    },
    {
        vietnameseSentence: "Tôi đã quen với việc thức dậy sớm vào buổi sáng mùa đông.",
        referenceAnswer: "I am used to waking up early on winter mornings.",
        alternativeAnswers: ["I have gotten used to getting up early in the winter mornings."],
        level: "B1",
        topic: "Daily Life",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["used to waking up", "early"],
    },
    {
        vietnameseSentence: "Báo cáo này cần phải được nộp trước 5 giờ chiều nay.",
        referenceAnswer: "This report must be submitted before 5 PM today.",
        alternativeAnswers: ["This report needs to be handed in by 5 PM today."],
        level: "B1",
        topic: "Work",
        grammarTopic: "Passive Voice",
        difficulty: "medium",
        keywords: ["must be submitted", "before 5 PM"],
    },
    {
        vietnameseSentence: "Bạn đã từng đi du lịch nước ngoài một mình bao giờ chưa?",
        referenceAnswer: "Have you ever traveled abroad alone?",
        alternativeAnswers: ["Have you ever traveled overseas on your own?", "Have you ever been abroad by yourself?"],
        level: "B1",
        topic: "Travel",
        grammarTopic: "Present Perfect",
        difficulty: "medium",
        keywords: ["have you ever traveled abroad", "alone"],
    },
    {
        vietnameseSentence: "Ô nhiễm không khí đang trở thành một vấn đề nghiêm trọng ở các thành phố lớn.",
        referenceAnswer: "Air pollution is becoming a serious problem in major cities.",
        alternativeAnswers: ["Air pollution is turning into a grave issue in big cities."],
        level: "B1",
        topic: "Environment",
        grammarTopic: "Present Continuous",
        difficulty: "medium",
        keywords: ["air pollution", "serious problem", "major cities"],
    },
    {
        vietnameseSentence: "Tôi rất mong chờ được gặp lại bạn vào kỳ nghỉ hè này.",
        referenceAnswer: "I am looking forward to seeing you again this summer vacation.",
        alternativeAnswers: ["I look forward to meeting you again this summer holiday."],
        level: "B1",
        topic: "Relationships",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "medium",
        keywords: ["looking forward to seeing", "summer vacation"],
    },
    {
        vietnameseSentence: "Thay vì đi ăn nhà hàng, chúng tôi tự nấu bữa tối ở nhà.",
        referenceAnswer: "Instead of going to a restaurant, we cooked dinner at home.",
        alternativeAnswers: ["Rather than eating out, we prepared dinner at home ourselves."],
        level: "B1",
        topic: "Food",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "medium",
        keywords: ["instead of going", "cooked dinner at home"],
    },
    {
        vietnameseSentence: "Chiếc điện thoại thông minh này được trang bị máy ảnh độ phân giải cao.",
        referenceAnswer: "This smartphone is equipped with a high-resolution camera.",
        alternativeAnswers: ["This smartphone features a high-definition camera."],
        level: "B1",
        topic: "Technology",
        grammarTopic: "Passive Voice",
        difficulty: "medium",
        keywords: ["equipped with", "high-resolution camera"],
    },
    {
        vietnameseSentence: "Nếu tôi biết số điện thoại của bạn, tôi đã gọi cho bạn rồi.",
        referenceAnswer: "If I had known your phone number, I would have called you.",
        alternativeAnswers: ["Had I known your number, I would have phoned you."],
        level: "B1",
        topic: "Relationships",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["if I had known", "would have called"],
    },
    {
        vietnameseSentence: "Tập thể dục đều đặn giúp bạn giảm căng thẳng và cải thiện sức khỏe.",
        referenceAnswer: "Exercising regularly helps you reduce stress and improve your health.",
        alternativeAnswers: ["Regular exercise helps reduce stress levels and improves health."],
        level: "B1",
        topic: "Health",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "medium",
        keywords: ["exercising regularly", "reduce stress", "improve health"],
    },
    {
        vietnameseSentence: "Tôi tự hỏi liệu chúng ta có thể dời cuộc họp sang thứ Sáu được không.",
        referenceAnswer: "I wonder whether we could reschedule the meeting to Friday.",
        alternativeAnswers: ["I wonder if we can postpone the meeting until Friday."],
        level: "B1",
        topic: "Business",
        grammarTopic: "Modal Verbs",
        difficulty: "medium",
        keywords: ["wonder whether", "reschedule the meeting"],
    },
    {
        vietnameseSentence: "Nhà hàng mà chúng ta đã ăn tối hôm qua vừa mới khai trương tuần trước.",
        referenceAnswer: "The restaurant where we had dinner yesterday just opened last week.",
        alternativeAnswers: ["The restaurant that we dined at yesterday opened only last week."],
        level: "B1",
        topic: "Food",
        grammarTopic: "Relative Clauses",
        difficulty: "medium",
        keywords: ["the restaurant where we had dinner", "just opened"],
    },
    {
        vietnameseSentence: "Bạn có phiền mở cửa sổ giúp tôi một lát được không?",
        referenceAnswer: "Would you mind opening the window for me for a moment?",
        alternativeAnswers: ["Do you mind opening the window for a while?"],
        level: "B1",
        topic: "Daily Life",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "medium",
        keywords: ["would you mind opening", "the window"],
    },
    {
        vietnameseSentence: "Kể từ khi áp dụng công nghệ mới, năng suất làm việc đã tăng đáng kể.",
        referenceAnswer: "Since adopting new technology, productivity has increased significantly.",
        alternativeAnswers: ["Work productivity has risen considerably since the introduction of new technology."],
        level: "B1",
        topic: "Technology",
        grammarTopic: "Present Perfect",
        difficulty: "medium",
        keywords: ["since adopting", "productivity has increased"],
    },

    // B2 (20 questions)
    {
        vietnameseSentence: "Chính sự kiên trì và cống hiến không ngừng đã giúp cô ấy đạt được học bổng.",
        referenceAnswer: "It was her persistence and relentless dedication that helped her secure the scholarship.",
        alternativeAnswers: ["Her perseverance and unwavering dedication enabled her to win the scholarship."],
        level: "B2",
        topic: "Education",
        grammarTopic: "Relative Clauses",
        difficulty: "hard",
        keywords: ["persistence", "dedication", "secure the scholarship"],
    },
    {
        vietnameseSentence: "Trừ khi các biện pháp nghiêm ngặt được thực thi, nếu không thì ô nhiễm nhựa sẽ tiếp tục đe dọa sinh vật biển.",
        referenceAnswer: "Unless strict measures are enforced, plastic pollution will continue to threaten marine life.",
        alternativeAnswers: ["If stringent measures are not implemented, plastic pollution will keep endangering marine ecosystems."],
        level: "B2",
        topic: "Environment",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["unless strict measures", "enforced", "threaten marine life"],
    },
    {
        vietnameseSentence: "Anh ấy bị chỉ trích vì đã không nộp báo cáo tài chính đúng hạn.",
        referenceAnswer: "He was criticized for not having submitted the financial report on time.",
        alternativeAnswers: ["He faced criticism for failing to submit the financial report on schedule."],
        level: "B2",
        topic: "Business",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["was criticized for", "financial report", "on time"],
    },
    {
        vietnameseSentence: "Không những anh ấy thông thạo tiếng Anh mà anh ấy còn có thể giao tiếp trôi chảy bằng tiếng Nhật.",
        referenceAnswer: "Not only is he fluent in English, but he can also communicate fluently in Japanese.",
        alternativeAnswers: ["Not only does he speak English fluently, but he is also proficient in Japanese."],
        level: "B2",
        topic: "Education",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["not only is he fluent", "communicate fluently"],
    },
    {
        vietnameseSentence: "Dự án lẽ ra đã hoàn thành sớm hơn nếu đội ngũ không gặp phải các trục trặc kỹ thuật.",
        referenceAnswer: "The project would have been completed earlier had the team not encountered technical glitches.",
        alternativeAnswers: ["The project could have been finished sooner if the team had not run into technical issues."],
        level: "B2",
        topic: "Technology",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["would have been completed", "technical glitches"],
    },
    {
        vietnameseSentence: "Bất chấp những khó khăn ban đầu về mặt kinh tế, công ty khởi nghiệp đã nhanh chóng mở rộng quy mô.",
        referenceAnswer: "Despite initial financial difficulties, the startup scaled up rapidly.",
        alternativeAnswers: ["In spite of early economic hurdles, the startup company expanded rapidly."],
        level: "B2",
        topic: "Business",
        grammarTopic: "Prepositions",
        difficulty: "medium",
        keywords: ["despite initial financial difficulties", "scaled up rapidly"],
    },
    {
        vietnameseSentence: "Người quản lý nhấn mạnh tầm quan trọng của việc duy trì cân bằng giữa công việc và cuộc sống.",
        referenceAnswer: "The manager emphasized the importance of maintaining a healthy work-life balance.",
        alternativeAnswers: ["The manager highlighted how crucial it is to maintain work-life balance."],
        level: "B2",
        topic: "Work",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "medium",
        keywords: ["emphasized the importance", "work-life balance"],
    },
    {
        vietnameseSentence: "Người ta ước tính rằng hơn 60% dân số sẽ sinh sống tại các khu vực thành thị vào năm 2050.",
        referenceAnswer: "It is estimated that over 60% of the population will reside in urban areas by 2050.",
        alternativeAnswers: ["Over 60 percent of the population is projected to live in urban areas by 2050."],
        level: "B2",
        topic: "Environment",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["it is estimated that", "urban areas", "by 2050"],
    },
    {
        vietnameseSentence: "Ngay khi bước chân vào khán phòng, cô ấy đã nhận ra một sự im lặng kỳ lạ.",
        referenceAnswer: "No sooner had she entered the auditorium than she noticed a peculiar silence.",
        alternativeAnswers: ["Hardly had she stepped into the auditorium when she became aware of a strange silence."],
        level: "B2",
        topic: "Entertainment",
        grammarTopic: "Past Simple",
        difficulty: "hard",
        keywords: ["no sooner had", "auditorium", "peculiar silence"],
    },
    {
        vietnameseSentence: "Trí tuệ nhân tạo đang biến đổi cách thức các doanh nghiệp tương tác với khách hàng của họ.",
        referenceAnswer: "Artificial intelligence is transforming the way businesses interact with their customers.",
        alternativeAnswers: ["AI is revolutionizing how enterprises engage with their clientele."],
        level: "B2",
        topic: "Technology",
        grammarTopic: "Relative Clauses",
        difficulty: "medium",
        keywords: ["artificial intelligence", "transforming the way", "interact"],
    },
    {
        vietnameseSentence: "Giáo sư gợi ý rằng sinh viên nên tiến hành nghiên cứu sâu hơn trước khi đưa ra kết luận.",
        referenceAnswer: "The professor suggested that students conduct further research before drawing conclusions.",
        alternativeAnswers: ["The professor recommended that students do in-depth research prior to concluding."],
        level: "B2",
        topic: "Education",
        grammarTopic: "Reported Speech",
        difficulty: "hard",
        keywords: ["suggested that students conduct", "drawing conclusions"],
    },
    {
        vietnameseSentence: "Việc lạm dụng mạng xã hội có thể tác động tiêu cực đến sức khỏe tinh thần của thanh thiếu niên.",
        referenceAnswer: "The excessive use of social media can adversely affect teenagers' mental health.",
        alternativeAnswers: ["Overusing social media may have a detrimental impact on adolescent psychological well-being."],
        level: "B2",
        topic: "Health",
        grammarTopic: "Modal Verbs",
        difficulty: "medium",
        keywords: ["excessive use", "adversely affect", "mental health"],
    },
    {
        vietnameseSentence: "Hầu hết các chuyên gia đều đồng ý rằng chế độ ăn dựa trên thực vật mang lại nhiều lợi ích tim mạch.",
        referenceAnswer: "Most experts agree that a plant-based diet offers numerous cardiovascular benefits.",
        alternativeAnswers: ["The majority of specialists concur that plant-based nutrition provides substantial heart health benefits."],
        level: "B2",
        topic: "Food",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "medium",
        keywords: ["plant-based diet", "cardiovascular benefits"],
    },
    {
        vietnameseSentence: "Chúng tôi đã phải hủy chuyến bay do điều kiện thời tiết khắc nghiệt ngoài dự kiến.",
        referenceAnswer: "We had to cancel our flight owing to unexpected severe weather conditions.",
        alternativeAnswers: ["We were forced to call off our flight due to unforeseen adverse weather."],
        level: "B2",
        topic: "Travel",
        grammarTopic: "Prepositions",
        difficulty: "medium",
        keywords: ["cancel flight", "owing to", "severe weather"],
    },
    {
        vietnameseSentence: "Nếu bạn đã nghe theo lời khuyên của bác sĩ thì bây giờ bạn đã không cảm thấy mệt mỏi như thế này.",
        referenceAnswer: "If you had followed the doctor's advice, you would not be feeling this exhausted now.",
        alternativeAnswers: ["Had you listened to the doctor, you wouldn't feel so fatigued right now."],
        level: "B2",
        topic: "Health",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["if you had followed", "would not be feeling"],
    },
    {
        vietnameseSentence: "Thỏa thuận thương mại này dự kiến sẽ thúc đẩy kim ngạch xuất khẩu của cả hai quốc gia.",
        referenceAnswer: "This trade agreement is expected to boost the export turnover of both nations.",
        alternativeAnswers: ["This commercial accord is anticipated to stimulate bilateral export volume."],
        level: "B2",
        topic: "Business",
        grammarTopic: "Passive Voice",
        difficulty: "medium",
        keywords: ["trade agreement", "expected to boost", "export turnover"],
    },
    {
        vietnameseSentence: "Bất kể bạn chọn con đường nào, bạn cũng phải chuẩn bị tinh thần đối mặt với thử thách.",
        referenceAnswer: "Regardless of which path you choose, you must be prepared to confront challenges.",
        alternativeAnswers: ["No matter what route you take, you need to brace yourself for difficulties."],
        level: "B2",
        topic: "Daily Life",
        grammarTopic: "Modal Verbs",
        difficulty: "hard",
        keywords: ["regardless of which path", "prepared to confront"],
    },
    {
        vietnameseSentence: "Tài liệu này mật đến mức chỉ có giám đốc điều hành mới được phép truy cập.",
        referenceAnswer: "This document is so confidential that only the chief executive officer is permitted access.",
        alternativeAnswers: ["So confidential is this document that only the CEO is authorized to access it."],
        level: "B2",
        topic: "Work",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["so confidential that", "permitted access"],
    },
    {
        vietnameseSentence: "Cô ấy thừa nhận đã chia sẻ thông tin độc quyền với một đối thủ cạnh tranh.",
        referenceAnswer: "She admitted to having shared proprietary information with a competitor.",
        alternativeAnswers: ["She acknowledged that she had disclosed proprietary data to a rival firm."],
        level: "B2",
        topic: "Business",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["admitted to having shared", "proprietary information", "competitor"],
    },
    {
        vietnameseSentence: "Người phụ nữ đứng đầu tổ chức từ thiện đã dành cả cuộc đời mình để đấu tranh cho quyền trẻ em.",
        referenceAnswer: "The woman who heads the charitable organization has dedicated her entire life to fighting for children's rights.",
        alternativeAnswers: ["The lady leading the charity has devoted her whole life to advocating for children's rights."],
        level: "B2",
        topic: "Relationships",
        grammarTopic: "Relative Clauses",
        difficulty: "hard",
        keywords: ["heads the charitable organization", "dedicated her entire life"],
    },

    // C1 (15 questions)
    {
        vietnameseSentence: "Chỉ khi người ta chứng kiến tận mắt những hậu quả tàn khốc của biến đổi khí hậu thì họ mới thực sự nhận thức được tính cấp bách của vấn đề.",
        referenceAnswer: "Only when people witness firsthand the catastrophic repercussions of climate change do they truly recognize the urgency of the matter.",
        alternativeAnswers: ["Not until individuals observe the devastating consequences of global warming firsthand do they appreciate the urgency."],
        level: "C1",
        topic: "Environment",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["only when", "catastrophic repercussions", "urgency of the matter"],
    },
    {
        vietnameseSentence: "Sự phát triển vượt bậc của điện toán lượng tử được kỳ vọng sẽ giải quyết những bài toán mã hóa phức tạp nhất hiện nay.",
        referenceAnswer: "The unprecedented advancement of quantum computing is anticipated to unravel today's most intricate cryptographic dilemmas.",
        alternativeAnswers: ["The remarkable breakthrough in quantum computing is expected to solve the most complex cryptography challenges."],
        level: "C1",
        topic: "Technology",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["unprecedented advancement", "quantum computing", "intricate cryptographic dilemmas"],
    },
    {
        vietnameseSentence: "Các nhà kinh tế học lập luận rằng việc thắt chặt chính sách tiền tệ có thể vô tình kìm hãm đà tăng trưởng bền vững.",
        referenceAnswer: "Economists contend that tightening monetary policy might inadvertently stifle sustainable economic expansion.",
        alternativeAnswers: ["Economists argue that monetary tightening could inadvertently dampen long-term economic growth."],
        level: "C1",
        topic: "Business",
        grammarTopic: "Reported Speech",
        difficulty: "hard",
        keywords: ["economists contend", "tightening monetary policy", "inadvertently stifle"],
    },
    {
        vietnameseSentence: "Bằng cách đa dạng hóa danh mục đầu tư, các nhà đầu tư tổ chức có thể giảm thiểu rủi ro biến động thị trường.",
        referenceAnswer: "By diversifying their investment portfolios, institutional investors can mitigate market volatility risks.",
        alternativeAnswers: ["Through portfolio diversification, institutional investors are able to minimize exposure to market volatility."],
        level: "C1",
        topic: "Business",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["diversifying investment portfolios", "mitigate market volatility"],
    },
    {
        vietnameseSentence: "Bất kể những lời chỉ trích gay gắt từ giới phê bình, cuốn tiểu thuyết đã trở thành một hiện tượng văn học đương đại.",
        referenceAnswer: "Notwithstanding fierce criticism from literary critics, the novel emerged as a contemporary literary phenomenon.",
        alternativeAnswers: ["Despite scathing reviews from critics, the book evolved into a landmark of contemporary literature."],
        level: "C1",
        topic: "Entertainment",
        grammarTopic: "Prepositions",
        difficulty: "hard",
        keywords: ["notwithstanding fierce criticism", "literary phenomenon"],
    },
    {
        vietnameseSentence: "Mức độ mà mạng xã hội thao túng dư luận đang là chủ đề tranh luận học thuật sôi nổi.",
        referenceAnswer: "The extent to which social media platforms manipulate public opinion remains a subject of intense scholarly debate.",
        alternativeAnswers: ["The degree to which digital platforms shape public consensus continues to provoke lively academic controversy."],
        level: "C1",
        topic: "Technology",
        grammarTopic: "Relative Clauses",
        difficulty: "hard",
        keywords: ["the extent to which", "manipulate public opinion", "scholarly debate"],
    },
    {
        vietnameseSentence: "Nếu giả định đó hóa ra là sai lầm, toàn bộ khuôn khổ lý thuyết sẽ phải được tái cấu trúc triệt để.",
        referenceAnswer: "Were that premise to prove unfounded, the entire theoretical framework would necessitate radical restructuring.",
        alternativeAnswers: ["Should that assumption turn out to be erroneous, the theoretical framework would require total overhaul."],
        level: "C1",
        topic: "Education",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["were that premise to prove unfounded", "radical restructuring"],
    },
    {
        vietnameseSentence: "Sự xói mòn các giá trị truyền thống thường bị quy cho sự đô thị hóa thần tốc và làn sóng toàn cầu hóa.",
        referenceAnswer: "The erosion of traditional values is frequently attributed to rapid urbanization and the influx of globalization.",
        alternativeAnswers: ["The decline of customary values is often ascribed to galloping urbanization alongside globalization."],
        level: "C1",
        topic: "Daily Life",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["erosion of traditional values", "attributed to rapid urbanization"],
    },
    {
        vietnameseSentence: "Không ai trong số các ứng viên đáp ứng đầy đủ các tiêu chí khắt khe do hội đồng tuyển dụng đề ra.",
        referenceAnswer: "None of the candidates fully met the stringent criteria established by the recruitment committee.",
        alternativeAnswers: ["Not a single candidate fulfilled the rigorous criteria set forth by the hiring board."],
        level: "C1",
        topic: "Work",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["none of the candidates", "stringent criteria", "recruitment committee"],
    },
    {
        vietnameseSentence: "Chính phủ đang xem xét việc ban hành các quy định nghiêm ngặt hơn nhằm ngăn chặn hành vi độc quyền thương mại.",
        referenceAnswer: "The government is contemplating the enactment of stricter regulations to curb monopolistic trade practices.",
        alternativeAnswers: ["Authorities are weighing the implementation of more stringent laws to prevent anti-competitive practices."],
        level: "C1",
        topic: "Business",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["contemplating the enactment", "curb monopolistic trade practices"],
    },
    {
        vietnameseSentence: "Việc tiếp xúc lâu dài với tiếng ồn cường độ cao có thể dẫn đến suy giảm thính lực không thể phục hồi.",
        referenceAnswer: "Prolonged exposure to high-intensity noise can lead to irreversible hearing impairment.",
        alternativeAnswers: ["Chronic exposure to intense noise levels may cause irreversible auditory loss."],
        level: "C1",
        topic: "Health",
        grammarTopic: "Modal Verbs",
        difficulty: "hard",
        keywords: ["prolonged exposure", "irreversible hearing impairment"],
    },
    {
        vietnameseSentence: "Đã có lúc công ty đứng trước bờ vực phá sản, nhưng chiến lược tái cơ cấu đã xoay chuyển tình thế ngoạn mục.",
        referenceAnswer: "There was a time when the corporation teetered on the brink of insolvency, but the restructuring strategy orchestrated a spectacular turnaround.",
        alternativeAnswers: ["At one point the firm was on the verge of bankruptcy, yet the turnaround strategy succeeded dramatically."],
        level: "C1",
        topic: "Business",
        grammarTopic: "Relative Clauses",
        difficulty: "hard",
        keywords: ["teetered on the brink of insolvency", "spectacular turnaround"],
    },
    {
        vietnameseSentence: "Người ta cho rằng sự đồng cảm là phẩm chất then chốt để xây dựng các mối quan hệ liên cá nhân bền chặt.",
        referenceAnswer: "Empathy is widely regarded as a quintessential attribute for cultivating enduring interpersonal relationships.",
        alternativeAnswers: ["Empathy is acknowledged to be a cornerstone for fostering long-lasting interpersonal bonds."],
        level: "C1",
        topic: "Relationships",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["quintessential attribute", "cultivating enduring interpersonal relationships"],
    },
    {
        vietnameseSentence: "Mặc dù đã có nhiều tiến bộ y học vượt bậc, căn bệnh này vẫn tiếp tục làm bối rối các nhà nghiên cứu dịch tễ.",
        referenceAnswer: "Notwithstanding groundbreaking medical advancements, this pathology continues to confound epidemiological researchers.",
        alternativeAnswers: ["Despite substantial medical progress, the disease continues to perplex epidemiologists worldwide."],
        level: "C1",
        topic: "Health",
        grammarTopic: "Prepositions",
        difficulty: "hard",
        keywords: ["groundbreaking medical advancements", "confound epidemiological researchers"],
    },
    {
        vietnameseSentence: "Điều quan trọng là hội đồng quản trị phải duy trì tính minh bạch tuyệt đối trong toàn bộ quá trình sáp nhập.",
        referenceAnswer: "It is imperative that the board of directors maintain absolute transparency throughout the merger process.",
        alternativeAnswers: ["It is crucial that the governing board uphold total transparency during the merger proceedings."],
        level: "C1",
        topic: "Business",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["imperative that", "maintain absolute transparency", "merger process"],
    },

    // C2 (15 questions)
    {
        vietnameseSentence: "Sự phụ thuộc quá mức vào các thuật toán dự báo rủi ro có thể ru ngủ các định chế tài chính vào một cảm giác an toàn giả tạo.",
        referenceAnswer: "An over-reliance on predictive risk algorithms risks lulling financial institutions into a perilous sense of complacency.",
        alternativeAnswers: ["Excessive dependence upon risk-forecasting algorithms may lull financial institutions into a false sense of security."],
        level: "C2",
        topic: "Business",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["over-reliance", "predictive risk algorithms", "perilous sense of complacency"],
    },
    {
        vietnameseSentence: "Bất kể những bất đồng ý thức hệ sâu sắc, các phái đoàn ngoại giao đã đạt được một hiệp ước hòa bình mang tính bước ngoặt.",
        referenceAnswer: "Transcending deep-seated ideological discord, the diplomatic delegations brokered a landmark peace accord.",
        alternativeAnswers: ["Despite profound ideological divides, the envoys successfully negotiated an unprecedented peace treaty."],
        level: "C2",
        topic: "Relationships",
        grammarTopic: "Prepositions",
        difficulty: "hard",
        keywords: ["transcending deep-seated ideological discord", "brokered a landmark peace accord"],
    },
    {
        vietnameseSentence: "Không thể phủ nhận rằng sự phát triển không được kiểm soát của đô thị đang gặm nhấm dần các vành đai sinh thái nguyên sinh.",
        referenceAnswer: "It is incontrovertible that unchecked urban sprawl is inexorably encroaching upon pristine ecological sanctuaries.",
        alternativeAnswers: ["There is no denying that uncontrolled suburban expansion relentlessly encroaches upon virgin ecosystems."],
        level: "C2",
        topic: "Environment",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["incontrovertible", "unchecked urban sprawl", "pristine ecological sanctuaries"],
    },
    {
        vietnameseSentence: "Hiếm khi nào một công trình triết học lại dung hòa được tính chặt chẽ của logic với sự bay bổng của mỹ học một cách tài tình như vậy.",
        referenceAnswer: "Seldom has a philosophical treatise reconciled logical rigor with aesthetic lyricism so masterfully.",
        alternativeAnswers: ["Rarely does a philosophical work harmonize analytical precision with poetic aesthetics in such a sublime manner."],
        level: "C2",
        topic: "Education",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["seldom has", "philosophical treatise", "reconciled logical rigor"],
    },
    {
        vietnameseSentence: "Sự phân nhánh phức tạp của luật bản quyền số đòi hỏi một cuộc cải cách lập pháp toàn diện trên quy mô toàn cầu.",
        referenceAnswer: "The labyrinthine ramifications of digital copyright law warrant comprehensive legislative overhaul on a global scale.",
        alternativeAnswers: ["The intricate intricacies of digital intellectual property dictate an overarching worldwide legal reform."],
        level: "C2",
        topic: "Technology",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["labyrinthine ramifications", "warrant comprehensive legislative overhaul"],
    },
    {
        vietnameseSentence: "Bằng việc mổ xẻ những tiền đề ngầm định của chủ nghĩa tiêu dùng, tác giả đã vạch trần nghịch lý của sự phồn vinh hiện đại.",
        referenceAnswer: "By deconstructing the implicit premises of consumerism, the author laid bare the paradoxes inherent in modern affluence.",
        alternativeAnswers: ["Dissecting the tacit assumptions underlying consumer culture, the writer exposed the contradictions of modern prosperity."],
        level: "C2",
        topic: "Daily Life",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["deconstructing implicit premises", "laid bare paradoxes of modern affluence"],
    },
    {
        vietnameseSentence: "Nếu không có sự cam kết kiên định từ các bên liên quan, sáng kiến bảo tồn thiên nhiên này chắc chắn sẽ đi vào ngõ cụt.",
        referenceAnswer: "Bereft of unwavering commitment from key stakeholders, this conservation initiative is destined to stall indefinitely.",
        alternativeAnswers: ["Without steadfast dedication among all stakeholders, this environmental endeavor is bound to end in futility."],
        level: "C2",
        topic: "Environment",
        grammarTopic: "Conditionals",
        difficulty: "hard",
        keywords: ["bereft of unwavering commitment", "destined to stall indefinitely"],
    },
    {
        vietnameseSentence: "Tác phẩm điện ảnh này đã thách thức các quy chuẩn tường thuật truyền thống bằng cách đan cài nhiều dòng thời gian phi tuyến tính.",
        referenceAnswer: "The cinematic masterpiece subverted conventional narrative tropes by intertwining multiple non-linear temporal trajectories.",
        alternativeAnswers: ["This film defied orthodox storytelling paradigms through an intricate weave of non-linear timelines."],
        level: "C2",
        topic: "Entertainment",
        grammarTopic: "Gerunds & Infinitives",
        difficulty: "hard",
        keywords: ["subverted conventional narrative tropes", "non-linear temporal trajectories"],
    },
    {
        vietnameseSentence: "Sự hội tụ giữa công nghệ sinh học và trí tuệ nhân tạo hứa hẹn mở ra kỷ nguyên y học chính xác từng cá nhân.",
        referenceAnswer: "The convergence of biotechnology and artificial intelligence portends a transformative epoch of bespoke precision medicine.",
        alternativeAnswers: ["The intersection of biotech and AI heralds a new era of highly personalized clinical intervention."],
        level: "C2",
        topic: "Health",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["convergence of biotechnology", "portends a transformative epoch", "bespoke precision medicine"],
    },
    {
        vietnameseSentence: "Nghịch lý thay, việc liên tục tiếp xúc với dòng thông tin vô tận lại làm xói mòn khả năng tập trung và tư duy phản biện sâu sắc.",
        referenceAnswer: "Paradoxically, perpetual exposure to an inexhaustible torrent of information erodes our capacity for sustained contemplation and critical inquiry.",
        alternativeAnswers: ["Ironically, constant inundation with data degrades one's aptitude for deep reflection and rigorous analysis."],
        level: "C2",
        topic: "Technology",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["paradoxically", "inexhaustible torrent of information", "sustained contemplation"],
    },
    {
        vietnameseSentence: "Bất kể mọi nỗ lực xoa dịu công chúng, bản báo cáo điều tra đã khơi lại những bức xúc âm ỉ bấy lâu trong xã hội.",
        referenceAnswer: "Notwithstanding all palliative public relations efforts, the investigative exposé reignited long-simmering societal indignation.",
        alternativeAnswers: ["Despite official attempts to placate the citizenry, the report unleashed deep-seated public rancor."],
        level: "C2",
        topic: "Relationships",
        grammarTopic: "Prepositions",
        difficulty: "hard",
        keywords: ["notwithstanding all palliative efforts", "reignited long-simmering societal indignation"],
    },
    {
        vietnameseSentence: "Vị thế dẫn đầu thị trường của tập đoàn không thể bị coi là điều hiển nhiên trong một bối cảnh cạnh tranh khốc liệt như hiện nay.",
        referenceAnswer: "The conglomerate's market supremacy cannot be taken for granted amidst such ruthless competitive dynamics.",
        alternativeAnswers: ["The firm's dominant market hegemony must not be presumed inviolable in today's fiercely competitive environment."],
        level: "C2",
        topic: "Business",
        grammarTopic: "Passive Voice",
        difficulty: "hard",
        keywords: ["market supremacy", "taken for granted", "ruthless competitive dynamics"],
    },
    {
        vietnameseSentence: "Sự phân hóa ngôn ngữ giữa các thế hệ phản ánh những biến chuyển sâu sắc trong cấu trúc văn hóa xã hội.",
        referenceAnswer: "Linguistic divergence across generational cohorts reflects profound tectonic shifts in sociocultural architecture.",
        alternativeAnswers: ["Generational linguistic variation mirrors profound mutations within the broader cultural fabric."],
        level: "C2",
        topic: "Education",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["linguistic divergence", "generational cohorts", "tectonic shifts"],
    },
    {
        vietnameseSentence: "Người đứng đầu đã khéo léo điều hòa các phe phái đối địch để xây dựng sự đồng thuận vững chắc cho dự luật mới.",
        referenceAnswer: "The leader adroitly mediated between adversarial factions to forge robust consensus on the proposed legislation.",
        alternativeAnswers: ["The chairperson skillfully reconciled conflicting parties to foster solid unanimity regarding the bill."],
        level: "C2",
        topic: "Work",
        grammarTopic: "Past Simple",
        difficulty: "hard",
        keywords: ["adroitly mediated", "adversarial factions", "forge robust consensus"],
    },
    {
        vietnameseSentence: "Khả năng phục hồi của hệ thống tài chính toàn cầu phụ thuộc mật thiết vào tính minh bạch và sự giám sát rủi ro liên tục.",
        referenceAnswer: "The resilience of the global financial architecture hinges critically upon heightened transparency and perpetual prudential oversight.",
        alternativeAnswers: ["The stability of international financial markets is contingent upon rigorous transparency and continuous regulatory vigilance."],
        level: "C2",
        topic: "Business",
        grammarTopic: "Subject-Verb Agreement",
        difficulty: "hard",
        keywords: ["resilience of global financial architecture", "hinges critically upon", "prudential oversight"],
    },
];

export const DEMO_ADMIN = {
    name: "System Administrator",
    email: "admin@example.com",
    password: "Admin@123",
    role: "admin" as const,
    level: "C2" as const,
    target: "Academic English" as const,
};

export const DEMO_USER = {
    name: "Nguyen Van A",
    email: "user@example.com",
    password: "User@123",
    role: "user" as const,
    level: "B1" as const,
    target: "IELTS" as const,
};
